import turtle
my_turtle = turtle.Turtle()
my_turtle.speed(1)
my_turtle.fillcolor("red")
my_turtle.begin_fill()
my_turtle.left(140)
my_turtle.forward(180)
my_turtle.circle(-90, 200)
my_turtle.left(120)
my_turtle.circle(-90, 200)
my_turtle.forward(180)
my_turtle.end_fill()
my_turtle.hideturtle()
turtle.done()
